config/routes.rb
Rails.application.routes.draw do
	resources :zombies do
  	resources :brains
	end
	
get '/duvan/cerebros', to: 'brains#index', as: 'brains'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brain.rb
class Brain < ApplicationRecord
	belongs_to :zombie
	
	validates :flavor, presence: true
	validates :iq, numericality: {only_integer: true, message: "Solo numeros enteros pls <3"}
end

app/models/zombie.rb
class Zombie < ApplicationRecord
	has_many :brains
	
	validates :bio, length: { maximum: 100 }
	validates :name, presence: true
	validates :age, numericality: {only_integer: true, message: "Solo numeros enteros pls <3"} 
  	validates :email, format: { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/ , message: "El formato del correo es invalido" }
	
	mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  # GET /brains
  # GET /brains.json
  def index
    @brains = Brain.all
  end

  # GET /brains/1
  # GET /brains/1.json
  def show
  end

  # GET /brains/new
  def new
    @brain = Brain.new
	@zombies = Zombie.all
  end

  # GET /brains/1/edit
  def edit
  end

  # POST /brains
  # POST /brains.json
  def create
	@zombie = Zombie.find(params[:zombie_id])
    @brain = @zombie.brains.create(brain_params)

    respond_to do |format|
      if @brain.save
        format.html { redirect_to @brain, notice: 'Brain was successfully created.' }
        format.json { render :show, status: :created, location: @brain }
		format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brains/1
  # PATCH/PUT /brains/1.json
  def update
    respond_to do |format|
      if @brain.update(brain_params)
        format.html { redirect_to @brain, notice: 'Brain was successfully updated.' }
        format.json { render :show, status: :ok, location: @brain }
      else
        format.html { render :edit }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brains/1
  # DELETE /brains/1.json
  def destroy
    @brain.destroy
    respond_to do |format|
      format.html { redirect_to brains_url, notice: 'Brain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brain
      @brain = Brain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brain_params
      params.require(:brain).permit(:flavor, :iq, :fresh, :zombie_id)
    end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
	@rotten_zombies = Zombie.where(rotten: true)
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:name, :bio, :age, :email, :rotten, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brains_helper.rb
module BrainsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/brains/_brain.html.erb
 
    <tr class="brains" id="brain_<%= brain.id %>">
      <td><%= time_ago_in_words(brain.created_at) %></td>
      <td><%= brain.flavor %></td>
      <td><%= brain.iq %></td>
      <td><%= brain.fresh %></td>
	</tr>
	 


app/views/brains/_form.html.erb
<%= form_with(model: brain, local: true) do |form| %>
  <% if brain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brain.errors.count, "error") %> prohibited this brain from being saved:</h2>

      <ul>
      <% brain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flavor %>
    <%= form.text_field :flavor, id: :brain_flavor %>
  </div>

<div class="field">
    <%= form.label :IQ %>
    <%= form.text_field :iq, id: :brain_iq %>
  </div>

<div class="field">
    <%= form.label :fresh %>
    <%= form.check_box :fresh, id: :brain_fresh %>
  </div>

<div class="field">
	<%= form.collection_select:zombie_id, Zombie.order(:name), :id, :name, include_blank: true %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brains/create.js.erb
var new_brain = $("<%= escape_javascript(render(:partial => @brain)) %>").hide();

$('#brains').prepend(new_brain);
$('#brain_<%= @brain.id %>').fadeIn('slow');
$('#new_brain')[0].reset();

app/views/brains/edit.html.erb
<h1>Editing Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Show', @brain, :class=> 'button primary' %> |
<%= link_to 'Back', brains_path, :class=> 'button primary' %>

app/views/brains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brains</h1>

<table>
  <thead>
    <tr>
      <th>Flavor</th>
      <th>IQ</th>
      <th>Fresh</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brains.each do |brain| %>
      <tr>
        <td><%= brain.flavor %></td>
        <td><%= brain.iq %></td>
        <td>
			<% if brain.fresh %>
				<%= image_tag 'brains/f_brain.png', class: 'brains_fresh' %>
			<% else %>
				<%= image_tag 'brains/nf_brain.png', class: 'brains_fresh' %>
			<% end %>
		</td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/brains/new.html.erb
<h1>New Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Back', brains_path %>

app/views/brains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flavor:</strong>
  <%= @brain.flavor %>
</p>

<p>
  <strong>IQ:</strong>
  <%= @brain.iq %>
</p>

<p>
  <strong>Fresh:</strong>
  <%= @brain.fresh %>
</p>

<%= link_to 'Edit', edit_brain_path(@brain) %> |
<%= link_to 'Back', brains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<ul class="dropdown menu" data-dropdown-menu>
  <li>
    <a href="#">Zombies</a>
    <ul class="menu">
      <li><a href="#">Index Zombies</a></li>
      <li><a href="#">Agregar Zombies</a></li>
      <!-- ... -->
    </ul>
  </li>
</ul>
    <%= yield %>

  </body>
</html>

app/views/zombies/_form.html.erb
<div class="row">
<%= form_with(model: zombie, local: true) do |form| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field column medium-5">
    <%= form.label :name %>
    <%= form.text_field :name, id: :zombie_name %>
  </div>
	
  <div class="field column medium-5">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :zombie_bio %>
  </div>
	
	 <div class="field column medium-5">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, id: :zombie_avatar %>
  </div>

  <div class="field column medium-5">
    <%= form.label :age %>
    <%= form.number_field :age, id: :zombie_age %>
  </div>

  <div class="field column medium-5">
    <%= form.label :email %>
    <%= form.text_field :email, id: :zombie_email %>
  </div>

  <div class="field column medium-5">
    <%= form.label :rotten %>
    <%= form.check_box :rotten, id: :zombie_rotten %>
  </div>

  <div class="actions column medium-5">
    <%= form.submit :class=> 'button primary' %>
  </div>
<% end %>
</div>

app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to '< Back', zombies_path, :class=> 'button primary' %>
<%= link_to 'Show', @zombie, :class=> 'button primary' %> 

app/views/zombies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zombies</h1>

<table>
  <thead>
    <tr>
	  <th>Avatar</th>
      <th>Name</th>
      <th>Bio</th>
      <th>Age</th>
      <th>Email</th>
      <th>Rotten</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rotten_zombies.each do |zombie| %>
      <tr>
        <td><%= image_tag zombie.avatar , class: 'zombie_img' %></td>
        <td><%= zombie.name %></td>
        <td><%= zombie.bio %></td>
        <td><%= zombie.age %></td>
        <td><%= zombie.email %></td>
        <td><%= zombie.rotten ? "yes" : "no" %></td>
        <td><%= link_to 'Show', zombie, :class=> 'button primary tiny' %></td>
        <td><%= link_to 'Edit', edit_zombie_path(zombie) , :class=> 'button success tiny' %></td>
        <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } , :class=> 'button alert tiny'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zombie', new_zombie_path, :class=>"button primary" %>

app/views/zombies/new.html.erb
<h1>New Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path, :class=> 'primary button' %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="column medium-7 medium-centered">
	<div class="card hovercard">
		<div class="card-background">
			<%= image_tag @zombie.avatar %>
		</div>
		<div class="useravatar">
			<%= image_tag @zombie.avatar %>
		</div>
		<div class="card-info">
			<span class="card-title"><%= @zombie.name %></span>
		</div>
	</div>
	<ul class="info_u">
		<li class="bio">
			<span>Bio</span>
			<p><%= @zombie.bio %></p>
		</li>
		<li>
			<span>Age</span>
			<p><%= @zombie.age %></p>
		</li>
		<li>
			<span>Rotten</span>
			<p><%= @zombie.rotten %></p>
		</li>
		<li class="email">
			<span>Email</span>
			<p><%= @zombie.email %></p>
		</li>
	</ul>
</div>

<div id="brains">
	<table>
  <thead>
    <tr>
      <th width="200">Agregado</th>
      <th>Flavor</th>
      <th width="150">IQ</th>
      <th width="150">Fresh</th>
    </tr>
  </thead>
  <tbody>
	<%= render :partial => @zombie.brains.reverse %>
	    </tbody>
</table>
</div>

<%= form_for([@zombie, Brain.new], remote:true) do |f| %>
	<div class="field comuln medium-6 medium-centered">
		<%= f.label :flavor %>
		<%= f.text_field :flavor %>
	</div>

	<div class="field comuln medium-6 medium-centered">
		<%= f.label :iq %>
		<%= f.number_field :iq %>
	</div>

	<div class="field comuln medium-6 medium-centered">
		<%= f.label :fresh %>
		<%= f.check_box :fresh %>
	</div>

	<div class="actions comuln medium-6 medium-centered">
		<%= f.submit "Add Brain", :class=> 'button primary expanded' %>
	</div>
<% end %>

<%= link_to 'Edit', edit_zombie_path(@zombie), :class=>' button primary' %> |
<%= link_to 'Back', zombies_path, :class=> 'button primary' %>